@FrameSeen_HostAddress = http://localhost:5066

### GET SERIE BY ID 
GET {{FrameSeen_HostAddress}}/api/series/search?q=stranger
Accept: application/json

### ADD A SERIE

POST {{FrameSeen_HostAddress}}/api/series/
Accept: application/json
Content-Type: application/json

{
  
  "name": "Stranger Things",

}

### UPDATE A SERIE
POST {{FrameSeen_HostAddress}}/api/series/
Accept: application/json
Content-Type: application/json

{
  "name": "Game of Throwns",
}
### ADD
POST {{FrameSeen_HostAddress}}/api/series/
Accept: application/json
Content-Type: application/json

{
  
  "name": "Dexter",

}

### DELETE A SERIE
DELETE {{FrameSeen_HostAddress}}/api/series/2
Accept: application/json



### GET ALL USERS
GET {{FrameSeen_HostAddress}}/api/users
Accept: application/json

### Create user
POST {{FrameSeen_HostAddress}}/api/users
Content-Type: application/json

{
  "name": "Levi",
  "email": "levi@email.com",
  "password": "123456"
}

### Update user
PUT {{FrameSeen_HostAddress}}/api/users/1
Content-Type: application/json

{
  "name": "Levi Updated",
  "email": "levi@email.com",
  "password": "123456"
}

### Delete user
DELETE {{FrameSeen_HostAddress}}/api/users/1